-- ─── جدول العملاء التجاريين ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients` (
  `id`             INT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id`      INT,
  `name`           VARCHAR(255) NOT NULL,
  `phone`          VARCHAR(100),
  `phone2`         VARCHAR(100),
  `email`          VARCHAR(255),
  `address`        TEXT,
  `city`           VARCHAR(100),
  `region`         VARCHAR(100),
  `tax_number`     VARCHAR(100),
  `commercial_reg` VARCHAR(100),
  `payment_terms`  VARCHAR(100),
  `credit_limit`   DECIMAL(14,2) DEFAULT 0,
  `total_orders`   INT DEFAULT 0,
  `total_sales`    DECIMAL(14,2) DEFAULT 0,
  `total_paid`     DECIMAL(14,2) DEFAULT 0,
  `notes`          TEXT,
  `is_active`      TINYINT(1) DEFAULT 1,
  `created_at`     DATETIME NOT NULL,
  `updated_at`     DATETIME NOT NULL,
  INDEX idx_clients_tenant (`tenant_id`),
  INDEX idx_clients_name   (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
